export default [
        {
            "id": 1,
            "firstName": "Sofia",
            "lastName": "Candiani",
            "quote": "Live the questions now. Perhaps then, someday far in the future, you will gradually, without even noticing it, live your way into the answer.",
            "quoteAuthor": "-Rainer Maria Rilke",
            "github": "https://github.com/sncandiani/",
            "linkedIn": "https://www.linkedin.com/in/sofiancandiani/",
            "portfolio": "https://sncandiani.github.io/",
            "email": "sofiancandiani@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 2,
            "firstName": "Keith",
            "lastName": "Potempa",
            "quote": "We are all apprentices in a craft where no one ever becomes a master.",
            "quoteAuthor": "-Ernest Hemingway",
            "github": "https://github.com/keithrpotempa",
            "linkedIn": "https://www.linkedin.com/in/keithrpotempa/",
            "portfolio": "https://keithpotempa.com/",
            "email": "keithrpotempa@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 3,
            "firstName": "Landon",
            "lastName": "Morgan",
            "quote": "i was so woried about wat i woud become in the future that i didnt realize i can be anything i want to be right now",
            "quoteAuthor": "-jonny sun",
            "github": "https://github.com/iandonmorgan",
            "linkedIn": "https://www.linkedin.com/in/landolake/",
            "portfolio": "https://iandonmorgan.github.io/",
            "email": "morganlandon@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 4,
            "firstName": "Matthew",
            "lastName": "Reeds",
            "quote": "Trust the wait. Embrace the uncertainty. Enjoy the beauty of becoming. When nothing is certain, anything is possible.",
            "quoteAuthor": "-Mandy Hale",
            "github": "https://github.com/MReeds",
            "linkedIn": "https://www.linkedin.com/in/mreeds/",
            "portfolio": "",
            "email": "mattlreeds@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 5,
            "firstName": "Dustin",
            "lastName": "Murdock",
            "quote": "All we have to decide is what to do with the time that is given us.",
            "quoteAuthor": "-J.R.R. Tolkien",
            "github": "https://github.com/MurdockDM",
            "linkedIn": "https://www.linkedin.com/in/dustinmurdock/",
            "portfolio": "",
            "email": "dmurdock2@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 6,
            "firstName": "Alyssa",
            "lastName": "Nycum",
            "quote": "What you do makes a difference, and you have to decide what kind of difference you want to make.",
            "quoteAuthor": " -Jane Goodall",
            "github": "https://github.com/alyssanycum",
            "linkedIn": "https://www.linkedin.com/in/alyssanycum/",
            "portfolio": "https://alyssanycum.github.io/",
            "email": "alyssa.nycum@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 7,
            "firstName": "Mollie",
            "lastName": "Goforth",
            "quote": "You sort of start thinking anything's possible if you've got enough nerve.",
            "quoteAuthor": "-Ginny Weasley",
            "github": "https://github.com/molliegoforth818",
            "linkedIn": "https://www.linkedin.com/in/molliegoforth818/",
            "portfolio": "",
            "email": "molliegoforth818@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 8,
            "firstName": "Kurt",
            "lastName": "Krafft",
            "quote": "True terror is to wake up one morning and discover that your high school class is running the country.",
            "quoteAuthor": "-Kurt Vonnegut",
            "github": "https://github.com/kurtkrafft1",
            "linkedIn": "https://www.linkedin.com/in/kurtkrafft/",
            "portfolio": "https://kurtkrafft1.github.io/",
            "email": "kurtkrafft3@gmail.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 9,
            "firstName": "Tyler",
            "lastName": "Simeone",
            "quote": "It's fine to celebrate success but it is more important to heed the lessons of failure.",
            "quoteAuthor": "Bill Gates",
            "email": "tyler.simeone@gmail.com(opens in new tab)",
            "github": "https://github.com/tyler-simeone",
            "linkedIn": "https://www.linkedin.com/in/tylersimeone",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "TylerSimeone-resume.pdf",
            "capstoneURL": ""
        },
        {
            "id": 10,
            "firstName": "Chase",
            "lastName": "Sullins",
            "quote": "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.",
            "quoteAuthor": "Viktor E. Frankl",
            "email": "jcsullins222@yahoo.com(opens in new tab)",
            "github": "https://github.com/ChaseSully222",
            "linkedIn": "https://www.linkedin.com/in/chasesullins/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "ChaseSullins-resume.pdf",
            "capstoneURL": ""
        },
        {
            "id": 11,
            "firstName": "Cooper",
            "lastName": "Nichols",
            "quote": "Sometimes a hypocrite is just a man in the process of changing.",
            "quoteAuthor": "Brandon Sanderson",
            "email": "coopnich92@gmail.com(opens in new tab)",
            "github": "https://github.com/CoopNich",
            "linkedIn": "https://www.linkedin.com/in/coopnich/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "CooperNichols-resume.pdf",
            "capstoneURL": ""
        },
        {
            "id": 12,
            "firstName": "Castle",
            "lastName": "Crawford",
            "quote": "Do or do not. There is no try.",
            "quoteAuthor": "Yoda",
            "email": "castlecrawford13@gmail.com(opens in new tab)",
            "github": "https://github.com/castlesmadeofcode",
            "linkedIn": "linkedin.com/in/castlecrawford13/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "resume": "CastleCrawford-resume.pdf",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 13,
            "firstName": "Matthew",
            "lastName": "Kroeger",
            "quote": "<quote>TODO: PUT QUOTE HERE</quote>",
            "quoteAuthor": "Me",
            "email": "matt.kroogz@gmail.com(opens in new tab)",
            "github": "https://github.com/mKroogz",
            "linkedIn": "https://www.linkedin.com/in/matthewkroeger/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 14,
            "firstName": "Matthew",
            "lastName": "Blagg",
            "quote": "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.",
            "quoteAuthor": "Ernest Hemingway",
            "email": "matthewscottblagg@gmail.com(opens in new tab)",
            "github": "https://github.com/MatthewScott32",
            "linkedIn": "https://www.linkedin.com/in/matthew-blagg/",
            "portfolio": "https://matthewscott32.github.io/matthewblagg.github.io/",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 15,
            "firstName": "Andrew",
            "lastName": "Green",
            "quote": "Believe in yourself, who else (is going to) believe in you?... Believe in yourself, health is wealth.",
            "quoteAuthor": "2 Chainz",
            "email": "green.andrew.b@gmail.com(opens in new tab)",
            "github": "https://github.com/agreen2601",
            "linkedIn": "https://www.linkedin.com/in/andrew--green/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 16,
            "firstName": "Cody",
            "lastName": "Murdock",
            "quote": "Without change something sleeps inside us and seldom awakens. The sleeper must awaken.",
            "quoteAuthor": "―Frank Herbert, Dune",
            "email": "warhammer4563@gmail.com",
            "github": "https://github.com/RockMurdock",
            "linkedIn": "https://www.linkedin.com/in/cody-murdock-a7310bb5/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 17,
            "firstName": "Matthew",
            "lastName": "Baker",
            "quote": "How can sky be the limit when there's footprints on the moon?",
            "quoteAuthor": "-Sir Robert Bryson Hall II",
            "email": "mattbaker2281@gmail.com",
            "github": "https://github.com/matthewbaker22",
            "linkedIn": "https://www.linkedin.com/in/matthewbaker20/",
            "portfolio": "https://matthewbaker22.github.io/",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 18,
            "firstName": "Trinity",
            "lastName": "Terry",
            "quote": "One day there won't be female leaders. There will just be leaders.",
            "quoteAuthor": "",
            "email": "trinitycterry@gmail.com",
            "github": "https://github.com/TrinityTerry",
            "linkedIn": "https://www.linkedin.com/in/trinityterry/",
            "portfolio": "https://trinitychristiana.netlify.app/",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 19,
            "firstName": "Mike",
            "lastName": "Prince",
            "quote": "Alice: This is impossible. The Mad Hatter: Only if you believe it is.",
            "quoteAuthor": "",
            "email": "michaelprince3@gmail.com",
            "github": "https://github.com/michaelprince3",
            "linkedIn": "www.linkedin.com/in/michaelprince3",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 20,
            "firstName": "Katie",
            "lastName": "Wohl",
            "quote": "Perhaps there is a language which is not made of words and everything in the world understands it.",
            "quoteAuthor": "-Frances Hodgson Burnett",
            "email": "ktwohl@gmail.com",
            "github": "https://github.com/kwohl",
            "linkedIn": "https://www.linkedin.com/in/katie-wohl/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 21,
            "firstName": "Bito",
            "lastName": "Mann",
            "quote": "If you get tired, learn to rest, not to quit.",
            "quoteAuthor": " ― Banksy",
            "email": "bito@bitomann.com",
            "github": "https://github.com/bitomann?tab=repositories",
            "linkedIn": "https://www.linkedin.com/in/bitomann/",
            "portfolio": "bitomann.com",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 22,
            "firstName": "Michael",
            "lastName": "Clark",
            "quote": "I want to stay as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.",
            "quoteAuthor": "-Kurt Vonnegut",
            "email": "michaelclarknashville@protonmail.com",
            "github": "https://github.com/mister-michael",
            "linkedIn": "https://www.linkedin.com/in/michaelclarknashville/",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 23,
            "firstName": "Matt",
            "lastName": "Crook",
            "quote": "Fill the unforgiving minute with sixty seconds worth of distance run.",
            "quoteAuthor": "- Rudyard Kipling",
            "email": "matt.crook11@gmail.com",
            "github": "https://github.com/MattCrook",
            "linkedIn": "https://www.linkedin.com/in/mattcrook11/",
            "portfolio": "https://matt-crook-io.now.sh/",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 24,
            "firstName": "Jack",
            "lastName": "Parsons",
            "quote": "Doing the same thing over and over again and expecting different results is the definition of software development.",
            "quoteAuthor": " -Andy Collins",
            "email": "jcksnparsons@gmail.com",
            "github": "https://github.com/jcksnparsons",
            "linkedIn": "https://www.linkedin.com/in/jackson-parsons/",
            "portfolio": "",
            "proImg": "",
            "funImg": "s",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        },
        {
            "id": 25,
            "firstName": "Jeremy",
            "lastName": "Mattingly",
            "quote": "",
            "quoteAuthor": "",
            "email": "",
            "github": "",
            "linkedIn": "",
            "portfolio": "",
            "proImg": "",
            "funImg": "",
            "isHired": false,
            "resume": "",
            "capstoneURL": ""
        }
]
