export default [
          {
            "id": 1,
            "firstName": "Joe",
            "lastName": "Beans",
            "quote": "I will succeed because I am willing to fail more than most are willing to try.",
            "quoteAuthor": "",
            "github": "https://github.com/Belljeremiah",
            "linkedIn": "https://www.linkedin.com/in/belljeremiah/",
            "portfolio": "",
            "email": "jeremiah.bell812.topper@gmail.com",
            "proImg": "jeremiah_serious.png",
            "funImg": "jeremiah_fun.png",
            "isHired": false
          },
          {
            "id": 2,
            "firstName": "Joe",
            "lastName": "Beans",
            "quote": "The only wealth which you will keep forever is the wealth you have given away.",
            "quoteAuthor": "-Marcus Aurelius",
            "github": "https://github.com/rdbishop19",
            "linkedIn": "https://www.linkedin.com/in/ryandanielbishop/",
            "portfolio": "https://rdbishop19.github.io/",
            "email": "rdbishop06@gmail.com",
            "proImg": "ryan_bishop_serious.png",
            "funImg": "ryan_bishop_fun.png",
            "isHired": false
          },
          {
            "id": 3,
            "firstName": "Joe",
            "lastName": "Beans",
            "quote": "Strength does not come from winning.  Your struggles develop your strengths. When you go through hardships and decide not to surrender, that is strength.",
            "quoteAuthor": "-Arnold Schwarzenegger",
            "github": "https://github.com/MatthewScott32",
            "linkedIn": "https://www.linkedin.com/in/matthew-blagg/",
            "portfolio": "https://matthewblagg.github.io/",
            "email": "matthewscottblagg@gmail.com",
            "proImg": "matthew_serious.png",
            "funImg": "matthew_fun.png",
            "isHired": false
          },
          {
            "id": 4,
            "firstName": "Cassandra",
            "lastName": "Boyd",
            "quote": "The Elders of the Internet know who I am?!",
            "quoteAuthor": "-Jen",
            "email": "cassandra.bacon@gmail.com",
            "github": "https://github.com/CassieBoyd",
            "linkedIn": "https://www.linkedin.com/in/cassandra-boyd/",
            "portfolio": "https://cassieboyd.github.io/",
            "proImg": "cassandra_serious.png",
            "funImg": "cassandra_fun.png",
            "isHired": false
          },
          {
            "id": 5,
            "firstName": "Ken",
            "lastName": "Boyd",
            "quote": "I have learned all kinds of things from my many mistakes. The one thing I never learn is to stop making them.",
            "quoteAuthor": "-Nicomo Cosca, from Last Argument of Kings by Joe Abercrombie",
            "email": "brantleyjones74@gmail.com",
            "github": "https://github.com/klb417",
            "linkedIn": "https://www.linkedin.com/in/kenneth-lee-boyd/",
            "portfolio": "",
            "proImg": "kenneth_serious.png",
            "funImg": "kenneth_fun.png",
            "isHired": false
          },
          {
            "id": 6,
            "firstName": "Caroline",
            "lastName": "Brownlee",
            "quote": "Instructions for living a life. Pay attention. Be astonished. Tell about it.",
            "quoteAuthor": "-Mary Oliver",
            "email": "brownleecaroline@gmail.com",
            "github": "https://github.com/CarolineBrownlee",
            "linkedIn": "https://www.linkedin.com/in/caroline-brownlee/",
            "portfolio": "",
            "proImg": "caroline_serious.png",
            "funImg": "caroline_serious.png",
            "isHired": false
          },
          {
            "id": 7,
            "firstName": "Manila",
            "lastName": "Bui",
            "quote": "Let's be like water.",
            "quoteAuthor": "-Ye",
            "email": "manila.bui@gmail.com",
            "github": "https://github.com/manilabui",
            "linkedIn": "https://www.linkedin.com/in/manilabui/",
            "portfolio": "https://manilabui.com/",
            "proImg": "manila_serious.png",
            "funImg": "manila_fun.png",
            "isHired": false
          },
          {
            "id": 8,
            "firstName": "Kurt",
            "lastName": "Krafft",
            "quote": "True terror is to wake up one morning and discover that your high school class is running the country.",
            "quoteAuthor": "- Kurt Vonnegut",
            "email": "kurtkrafft3@gmail.com",
            "github": "https://github.com/kurtkrafft1",
            "linkedIn": "https://www.linkedin.com/in/kurtkrafft/",
            "portfolio": "https://kurtkrafft1.github.io/",
            "proImg": "kurt_serious.jpg",
            "funImg": "kurt_fun.jpg",
            "isHired": false,
            "resume": "KurtKrafft-resume.pdf",
            "capstoneURL": ""
          },
          {
            "id": 9,
            "firstName": "James",
            "lastName": "Chapman",
            "quote": "Insanity is doing the same thing, over and over again, but expecting different results.",
            "quoteAuthor": "",
            "email": "chapmanjamesg@gmail.com",
            "github": "https://github.com/chapmanjamesg",
            "linkedIn": "https://www.linkedin.com/in/james-g-chapman/",
            "portfolio": "https://chapmanjamesg.github.io/",
            "proImg": "james_serious.png",
            "funImg": "james_fun.png",
            "isHired": false
          },
          {
            "id": 10,
            "firstName": "Shawna",
            "lastName": "Chatfield",
            "quote": "This time, you've got to do something absolutely different from what you've ever done before.",
            "quoteAuthor": "-Michael Caine",
            "email": "chatfield.shc@gmail.com",
            "github": "https://github.com/schatfield",
            "linkedIn": "https://www.linkedin.com/in/shawna-chatfield/",
            "portfolio": "https://shawnachatfield.github.io/",
            "proImg": "shawna_serious.png",
            "funImg": "shawna_fun.png",
            "isHired": false
          },
          {
            "id": 11,
            "firstName": "Guy",
            "lastName": "Cherkesky",
            "quote": "If you build it, they will come.",
            "quoteAuthor": "",
            "email": "guy@cherkesky.com",
            "github": "https://github.com/cherkesky",
            "linkedIn": "https://www.linkedin.com/in/cherkesky/",
            "portfolio": "https://www.cherkesky.com",
            "proImg": "guy_serious.png",
            "funImg": "guy_fun.png",
            "isHired": false
          },
          {
            "id": 12,
            "firstName": "Ryan",
            "lastName": "Crowley",
            "quote": "Humility is not thinking less of yourself, but thinking of yourself less.",
            "quoteAuthor": "-C.S. Lewis",
            "email": "ryancrowleycode@gmail.com",
            "github": "https://github.com/RyanCrowleyCode",
            "linkedIn": "https://www.linkedin.com/in/ryancrowley03/",
            "portfolio": "https://ryancrowleycode.github.io/",
            "proImg": "ryan_crowley_serious.png",
            "funImg": "ryan_crowley_fun.png",
            "isHired": false
          },
          {
            "id": 13,
            "firstName": "Ryan",
            "lastName": "Cunningham",
            "quote": "Compare yourself to who you were yesterday, not to who someone else is today.",
            "quoteAuthor": "",
            "email": "rhc822@gmail.com",
            "github": "https://github.com/rhc822/",
            "linkedIn": "https://linkedin.com/in/rhc822",
            "portfolio": "https://rhc822.github.io/",
            "proImg": "ryan_cunningham_serious.png",
            "funImg": "ryan_cunningham_serious.png",
            "isHired": false
          },
          {
            "id": 14,
            "firstName": "Chase",
            "lastName": "Fite",
            "quote": "Success is that moment when preparation meets opportunity.",
            "quoteAuthor": "",
            "email": "chasef7031@gmail.com",
            "github": "https://github.com/chase-fite",
            "linkedIn": "https://www.linkedin.com/in/chase-fite/",
            "portfolio": "https://github.com/chase-fite",
            "proImg": "chase_serious.png",
            "funImg": "chase_serious.png",
            "isHired": false
          },
          {
            "id": 15,
            "firstName": "Julian",
            "lastName": "Garcia",
            "quote": "Don’t cry because it’s over, smile because it happened.",
            "quoteAuthor": "-Dr. Seuss",
            "email": "Garcia.j.julian@gmail.com",
            "github": "https://github.com/Garcia-Julz",
            "linkedIn": "https://www.linkedin.com/in/julian-garcia/",
            "portfolio": "",
            "proImg": "julian_serious.png",
            "funImg": "julian_fun.png",
            "isHired": false
          },
          {
            "id": 16,
            "firstName": "Corri",
            "lastName": "Golden",
            "quote": "A legend is an old man with a cane known for what he used to do. I’m still doing it.”",
            "quoteAuthor": "-Miles Davis",
            "email": "brantleyjones74@gmail.com",
            "github": "https://github.com/corri-golden",
            "linkedIn": "https://www.linkedin.com/in/corri-golden/",
            "portfolio": "https://corri-golden.github.io/",
            "proImg": "corri_serious.png",
            "funImg": "corri_fun.png",
            "isHired": false
          },
          {
            "id": 17,
            "firstName": "Sophia",
            "lastName": "Hoffman",
            "quote": "The world is your oyster. Don’t choke on the pearl.",
            "quoteAuthor": "",
            "email": "sophiahoffman@hotmail.com",
            "github": "sophiahoffman@hotmail.com",
            "linkedIn": "https://www.linkedin.com/in/sophia-hoffman/",
            "portfolio": "",
            "proImg": "sophia_serious.png",
            "funImg": "sophia_fun.png",
            "isHired": false
          },
          {
            "id": 18,
            "firstName": "Charles",
            "lastName": "Jackson",
            "quote": "If you clean a vacuum cleaner, does that make you a vacuum cleaner?",
            "quoteAuthor": "",
            "email": "cpjackson572@gmail.com",
            "github": "https://github.com/CPJackson777",
            "linkedIn": "https://www.linkedin.com/in/charlespjackson/",
            "portfolio": "http://cpjackson777.github.io/",
            "proImg": "charles_serious.png",
            "funImg": "charles_fun.png",
            "isHired": false
          },
          {
            "id": 19,
            "firstName": "Michelle S",
            "lastName": "Johnson",
            "quote": "Always be yourself unless you can be Stitch, then always be Stitch.",
            "quoteAuthor": "",
            "email": "bob1234girl@gmail.com",
            "github": "https://github.com/stitchelle",
            "linkedIn": "https://www.linkedin.com/in/stitchelle/",
            "portfolio": "",
            "proImg": "michelle_serious.png",
            "funImg": "michelle_fun.png",
            "isHired": false
          }
        //   ,
        //   {
        //     "id": 20,
        //     "firstName": "Katie",
        //     "lastName": "Wohl",
        //     "quote": "Perhaps there is a language which is not made of words and everything in the world understands it.",
        //     "quoteAuthor": "-Frances Hodgson Burnett",
        //     "email": "ktwohl@gmail.com",
        //     "github": "https://github.com/kwohl",
        //     "linkedIn": "https://www.linkedin.com/in/katie-wohl/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false
        //   },
        //   {
        //     "id": 21,
        //     "firstName": "Bito",
        //     "lastName": "Mann",
        //     "quote": "If you get tired, learn to rest, not to quit.",
        //     "quoteAuthor": " ― Banksy",
        //     "email": "bito@bitomann.com",
        //     "github": "https://github.com/bitomann?tab=repositories",
        //     "linkedIn": "https://www.linkedin.com/in/bitomann/",
        //     "portfolio": "bitomann.com",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false
        //   },
        //   {
        //     "id": 22,
        //     "firstName": "Michael",
        //     "lastName": "Clark",
        //     "quote": "I want to stay as close to the edge as I can without going over. Out on the edge you see all kinds of things you can't see from the center.",
        //     "quoteAuthor": "-Kurt Vonnegut",
        //     "email": "michaelclarknashville@protonmail.com",
        //     "github": "https://github.com/mister-michael",
        //     "linkedIn": "https://www.linkedin.com/in/michaelclarknashville/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false
        //   },
        //   {
        //     "id": 23,
        //     "firstName": "Matt",
        //     "lastName": "Crook",
        //     "quote": "Fill the unforgiving minute with sixty seconds worth of distance run.",
        //     "quoteAuthor": "- Rudyard Kipling",
        //     "email": "matt.crook11@gmail.com",
        //     "github": "https://github.com/MattCrook",
        //     "linkedIn": "https://www.linkedin.com/in/mattcrook11/",
        //     "portfolio": "https://matt-crook-io.now.sh/",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false
        //   },
        //   {
        //     "id": 24,
        //     "firstName": "Jack",
        //     "lastName": "Parsons",
        //     "quote": "Doing the same thing over and over again and expecting different results is the definition of software development.",
        //     "quoteAuthor": " -Andy Collins",
        //     "email": "jcksnparsons@gmail.com",
        //     "github": "https://github.com/jcksnparsons",
        //     "linkedIn": "https://www.linkedin.com/in/jackson-parsons/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "s",
        //     "isHired": true
        //   },
        //   {
        //     "id": 25,
        //     "firstName": "Erin",
        //     "lastName": "Polley",
        //     "quote": "It is impossible to live without failing at something, unless you live so cautiously that you might as well not have lived at all.",
        //     "quoteAuthor": "-J.K. Rowling",
        //     "email": "erinepolley@gmail.com",
        //     "github": "https://github.com/erinepolley",
        //     "linkedIn": "https://www.linkedin.com/in/erinepolley/",
        //     "portfolio": "https://erinepolley.github.io/",
        //     "proImg": "erin_serious.png",
        //     "funImg": "erin_fun.png",
        //     "isHired": false
        //   },

        // {
        //     "id": 9,
        //     "firstName": "Tyler",
        //     "lastName": "Simeone",
        //     "quote": "It's fine to celebrate success but it is more important to heed the lessons of failure.",
        //     "quoteAuthor": "Bill Gates",
        //     "email": "tyler.simeone@gmail.com(opens in new tab)",
        //     "github": "https://github.com/tyler-simeone",
        //     "linkedIn": "https://www.linkedin.com/in/tylersimeone",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "TylerSimeone-resume.pdf",
        //     "capstoneURL": ""
        // },
        // {
        //     "id": 10,
        //     "firstName": "Chase",
        //     "lastName": "Sullins",
        //     "quote": "Everything can be taken from a man but one thing: the last of the human freedoms—to choose one’s attitude in any given set of circumstances, to choose one’s own way.",
        //     "quoteAuthor": "Viktor E. Frankl",
        //     "email": "jcsullins222@yahoo.com(opens in new tab)",
        //     "github": "https://github.com/ChaseSully222",
        //     "linkedIn": "https://www.linkedin.com/in/chasesullins/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "ChaseSullins-resume.pdf",
        //     "capstoneURL": ""
        // },
        // {
        //     "id": 11,
        //     "firstName": "Cooper",
        //     "lastName": "Nichols",
        //     "quote": "Sometimes a hypocrite is just a man in the process of changing.",
        //     "quoteAuthor": "Brandon Sanderson",
        //     "email": "coopnich92@gmail.com(opens in new tab)",
        //     "github": "https://github.com/CoopNich",
        //     "linkedIn": "https://www.linkedin.com/in/coopnich/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "CooperNichols-resume.pdf",
        //     "capstoneURL": ""
        // },
        // {
        //     "id": 12,
        //     "firstName": "Castle",
        //     "lastName": "Crawford",
        //     "quote": "Do or do not. There is no try.",
        //     "quoteAuthor": "Yoda",
        //     "email": "castlecrawford13@gmail.com(opens in new tab)",
        //     "github": "https://github.com/castlesmadeofcode",
        //     "linkedIn": "linkedin.com/in/castlecrawford13/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "resume": "CastleCrawford-resume.pdf",
        //     "isHired": true
        // },
        // {
        //     "id": 13,
        //     "firstName": "Matthew",
        //     "lastName": "Kroeger",
        //     "quote": "<quote>TODO: PUT QUOTE HERE</quote>",
        //     "quoteAuthor": "Me",
        //     "email": "matt.kroogz@gmail.com(opens in new tab)",
        //     "github": "https://github.com/mKroogz",
        //     "linkedIn": "https://www.linkedin.com/in/matthewkroeger/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "MatthewKroeger-resume.pdf",
        //     "capstoneURL": ""
        // },
        // {
        //     "id": 14,
        //     "firstName": "Matthew",
        //     "lastName": "Blagg",
        //     "quote": "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.",
        //     "quoteAuthor": "Ernest Hemingway",
        //     "email": "matthewscottblagg@gmail.com(opens in new tab)",
        //     "github": "https://github.com/MatthewScott32",
        //     "linkedIn": "https://www.linkedin.com/in/matthew-blagg/",
        //     "portfolio": "https://matthewscott32.github.io/matthewblagg.github.io/",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "MatthewBlagg-resume.pdf",
        //     "capstoneURL": ""
        //   },
        // {
        //     "id": 15,
        //     "firstName": "Andrew",
        //     "lastName": "Green",
        //     "quote": "Believe in yourself, who else (is going to) believe in you?... Believe in yourself, health is wealth.",
        //     "quoteAuthor": "2 Chainz",
        //     "email": "green.andrew.b@gmail.com(opens in new tab)",
        //     "github": "https://github.com/agreen2601",
        //     "linkedIn": "https://www.linkedin.com/in/andrew--green/",
        //     "portfolio": "",
        //     "proImg": "",
        //     "funImg": "",
        //     "isHired": false,
        //     "resume": "AndrewGreen-resume.pdf",
        //     "capstoneURL": ""
        // },
]
